### ISSUE TITLE
Array of empty items is empty

### ISSUE THREAD

**Issue by zebmason** [kushalpandya/JSONify#1]
Looks like
  if (json[this.name]) {
should be
  if (this.name in json) {
otherwise empty items get concatenated.

Must work out how to push to GitHub...

**Comment by kushalpandya** [comment]
@zebmason was in hurry may be that I did quick null check, would fix it, or may be you can submit a pull request :) Thanks anyway!

**Comment by zebmason** [comment]
Kushal

Forgot to say thank you for posting the code. Am surprised with myself that I managed to debug my problem as it’s the first time I’ve got the debugger working in a browser.

Haven’t quite managed managed to push to GitHub yet, was wasting time trying to push to a GitLab instance this afternoon.

Cheers

Zeb

**Comment by singhananya09** [comment]
I can take a look at this. :slightly_smiling_face:

**Comment by kushalpandya** [comment]
Fixed by #4
