### ISSUE TITLE
Multidepth array

### ISSUE THREAD

**Issue by alexbowers-tecmark** [kushalpandya/JSONify#2]
For example, these fields:

```
<input name="field[string][other_string]" />
<input name="field[string][more]" />
```

Will result in a broken array:

```
[field[string] => Array
        (
            [other_string] => 0,
            [more] => 0
        )
```

Where it should be

```
[field] => Array
    (
        [string] => Array
        (        
                [other_string] => 0,
                [more]
        )
    )
```

**Comment by kushalpandya** [comment]
Usually value of `name` attribute should be a plain string and should follow naming conventions similar to variable names in JS to avoid such conflicts, fixing this problem requires to add name sanitization within library, which undermines its simplicity and is beyond the scope of what this library does.

A good solution is to ensure that value of `name` attribute are escaped by page renderer (by stripping special characters like `.`, `[` or `]` before JS kicks in and JSONify methods are called.
