### ISSUE TITLE
Radio button seem to not work for dejsonify

### ISSUE THREAD

**Issue by onigetoc** [kushalpandya/JSONify#3]
Radio buttons seem to not work for dejsonify.
It may miss adding checked

https://jsfiddle.net/onigetoc/aapne9nv/2/

**Comment by onigetoc** [comment]
I just find out that using dejsonify give the same value to all radio button group

**Comment by onigetoc** [comment]
I tryed multiple method and it work only once.
i can fill the form with the right radio button checked. but if you change the radio choice or not and try to fill the form again, it do not work.
https://jsfiddle.net/onigetoc/f0f6ud60/4/

**Comment by kushalpandya** [comment]
Hi @onigetoc, I can confirm that it is a bug causing odd behavior with Radios and Checkbox both, and I'll be fixing it in a patch release soon. Although you're free to make a pull request :)

**Comment by onigetoc** [comment]
I tested something, do not know if it's safe but it work.

instead of using (Because it work only once)
`$this.attr('checked', true);`
i did
`$this.click();`
https://jsfiddle.net/onigetoc/f0f6ud60/9/

Simple Bootstrap demo: 
https://jsfiddle.net/onigetoc/49yzrs53/

**Comment by kushalpandya** [comment]
@onigetoc Calling `.click()` on fields will also trigger any click handlers bound to it and it may not be something you want while filling out form. Also, the modification you mentioned doesn't populate Checkboxes correctly, and [v0.3.1](https://github.com/kushalpandya/JSONify/releases/tag/v0.3.1) works fine in all cases around Radios and Checkboxes.

**Comment by onigetoc** [comment]
I just saw your update, and it work well, great.
